Name:SHREYA SATHISH
Roll No:23102C0019

In [20]:
# LECTURE 9: Calculations with Data Vectors (Addition, Subtraction, etc.)[cite: 2]

# Vector addition[cite: 2]
c(2, 3, 5, 7) + c(-2, -3, -5, 8)

[1]  0  0  0 15

In [21]:
# LECTURE 10: Power Operations, Integer & Modulo Divisions[cite: 2]

# Power operators (^ and **) with scalars[cite: 2]
2^3
2**3
2^0.5
2**0.5
2^-0.5

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [22]:
# Power operations with vectors[cite: 2]
c(2, 3, 5, 7)^2
c(2, 3, 5, 7)^c(2, 3)
c(1, 2, 3, 4, 5, 6)^c(2, 3, 4)
c(2, 3, 5, 7)^c(2, 3, 4) # Recycled with warning[cite: 2]

[1]  4  9 25 49

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [23]:
# Integer Division (%/%)[cite: 2]
2 %/% 2
5 %/% 2
7 %/% 3
c(2, 3, 5, 7) %/% 2
c(2, 3, 5, 7) %/% c(2, 3)
c(2, 3, 5) %/% c(2, 3) # Recycled with warning[cite: 2]

[1] 1

[1] 2

[1] 2

[1] 1 1 2 3

[1] 1 1 2 2

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [24]:
# Modulo Division (%%)[cite: 2]
2 %% 2
3 %% 2
7 %% 3
7 %% 4
c(2, 3, 5, 7) %% 2
c(2, 3, 5, 7) %% c(2, 3)
c(2, 3, 5) %% c(2, 3) # Recycled with warning[cite: 2]

[1] 0

[1] 1

[1] 1

[1] 3

[1] 0 1 1 1

[1] 0 0 1 1

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [25]:
# LECTURE 11: Built-in Functions and Assignments[cite: 2]

# Summary & Basic functions (scalars vs vectors)[cite: 2]
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 3.4

[1] 3.4

[1] -7.8

[1] -7.8

[1] 2

[1] 3

In [26]:
# Absolute values, Square roots, Sum, and Product[cite: 2]
abs(-4)
abs(c(-1, -2, -3, 4, 5))

sqrt(4)
sqrt(c(4, 9, 16, 25))

sum(c(2, 3, 5, 7))
prod(c(2, 3, 5, 7))

[1] 4

[1] 1 2 3 4 5

[1] 2

[1] 2 3 4 5

[1] 17

[1] 210

In [27]:
# Rounding[cite: 2]
round(1.23)
round(1.83)

[1] 1

[1] 2

In [28]:
# Logarithmic functions[cite: 2]
log(10)
log(exp(1))
log(c(10, 100, 1000))

log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

[1] 1

[1] 2

[1] 1 2 3

In [29]:
# Variable assignments and combined calculations[cite: 2]
x1 = c(1, 2, 3, 4)
x1
x2 = x1^2
x2

c(1, 2, 3, 4) + sum(c(1, 2, 3, 4)) * prod(c(1, 2))
sum(c(1, 2, 3, 4)) * prod(c(1, 2))
abs(c(1, 2, 3, 4) - sum(c(1, 2, 3, 4)) * prod(c(1, 2)))
c(1, 2, 3, 4) - sum(c(1, 2, 3, 4)) * prod(c(1, 2))

[1] 1 2 3 4

[1]  1  4  9 16

[1] 21 22 23 24

[1] 20

[1] 19 18 17 16

[1] -19 -18 -17 -16

In [30]:
# LECTURE 12: Matrices[cite: 2]

# Creating matrices (column-wise by default)[cite: 2]
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [31]:
# Accessing elements: x[row, col][cite: 2]
x[3, 2]

[1] 7

In [32]:
# Explicit column-wise entry[cite: 2]
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = FALSE)
x

# Row-wise entry[cite: 2]
y = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [33]:
# Matrix properties[cite: 2]
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [34]:
# Help documentation & documentation examples[cite: 2]
help("matrix")
is.matrix(as.matrix(1:10))
data(warpbreaks)
!is.matrix(warpbreaks)
warpbreaks[1:10, ]
as.matrix(warpbreaks[1:10, ])

[1] TRUE

[1] TRUE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M