Name:Shreya Sathish
Roll no:23102C0019

In [5]:
# LECTURE 18: Missing Data Handling[cite: 1]

x = NA
is.na(x)

x = c(11, NA, 13, NA)
is.na(x)

mean(x)
mean(x, na.rm = TRUE)

which(is.na(x))
sum(is.na(x))

complete.cases(x)
y = na.omit(x)
y
mean(y)

[1] TRUE

[1] FALSE  TRUE FALSE  TRUE

[1] NA

[1] 12

[1] 2 4

[1] 2

[1]  TRUE FALSE  TRUE FALSE

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] 12

In [4]:
# LECTURE 19: Conditional Executions (If and If-Else)[cite: 1]

x = 5
if (x > 4) x * 3

x = 3
if (x > 4) x * 3

x = 5
if (x > 4) {x * 3}

x = 3
if (x > 4) {x * 3}

x = 6
if(x > 3){
  print("The value is more than 3")
}

x = 2
if(x > 3){
  print("The value is more than 3")
}

x = 5
if ( x == 3 ) {x = x - 1} else {x = 2 * x}
x

x = 3
if ( x == 3 ) {x = x - 1} else {x = 2 * x}
x

x = 6
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

x = 2
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] 15

[1] 15

[1] "The value is more than 3"

[1] 10

[1] 2

[1] "The value is more than 3"
[1] "The value is less than 3"

In [6]:
#LECTURE 20: Nested If-Else and Ifelse()[cite: 1]

x = 5
if ( x == 3 ) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else { x = 2 * x }
x

x = 2
if ( x == 3 ) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else { x = 2 * x }
x

x = 3
if ( x == 3 ) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else { x = 2 * x }
x

x = 1:10
x
ifelse(x < 6, x^2, x + 1)

x = c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] 10

[1] 7

[1] 2

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

[1] "odd number"  "odd number"  "even number" "even number"

In [8]:
# LECTURE 21: Switch and Which Commands[cite: 1]

switch(2, "apple", "banana", "orange")
switch(1, "apple", "banana", "orange")

switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

switch(4, "apple", "banana", "orange")
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

x = c(10, 15, 8, 14, 6, 12)
x
which(x == 14)
which(x != 12)
which(x > 10)

x = matrix(nrow = 3, ncol = 3, data = 1:9)
x
which.min(x)
which.max(x)

which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

[1] "banana"

[1] "apple"

[1] "blue"

[1] 50

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3