In [1]:
print("Hello R Programming")

[1] "Hello R Programming"

In [2]:
print("The zero occurs at")
print(2*pi)
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [3]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [4]:
cat("Hello")
cat("\n")
cat("World")

Hello
World

In [5]:
d = date()

cat("Today's date is:", d, "\n")

Today's date is: Thu Sep 24 04:26:13 2026

In [6]:
x = 1:10

x

 [1]  1  2  3  4  5  6  7  8  9 10

In [7]:
cat(x, sep = " ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [8]:
cat(x, sep = " / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [9]:
x = 7

cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [10]:
x = 7

cat(
  "The square root of",
  x,
  "is approximately",
  format(sqrt(x), digits = 3),
  "\n"
)

The square root of 7 is approximately 2.65

In [11]:
evenno = c(2, 4, 6, 8, 10)

evenno

[1]  2  4  6  8 10

In [12]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [13]:
x = 1:10

cat(
  x,
  fill = 2,
  labels = paste("(", letters[1:10], "):")
)

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [14]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [15]:
paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "*"
)

[1] "Everybody*loves*R Programming."

In [17]:
paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "==="
)

[1] "Everybody===loves===R Programming."

In [18]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [19]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [20]:
names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [21]:
paste(
  names,
  "is",
  "a good",
  "person."
)

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [22]:
names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

paste(
  names,
  "is",
  "a good",
  "person.",
  collapse = ", and "
)

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

In [23]:
paste(
  1,
  " is first",
  2,
  " is second",
  3,
  " is third",
  sep = "#"
)

[1] "1# is first#2# is second#3# is third"

In [24]:
x = paste("Ex", 1:5, sep = "_")

x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [25]:
x = paste("Ex", 1:5, sep = "_")

x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [26]:
x = paste(
  "Ex",
  1:5,
  sep = "_",
  collapse = ""
)

x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [27]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [28]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [29]:
paste0(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [30]:
paste(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [34]:
x = "Hello World"

strsplit(x, split = " ")

[[1]]
[1] "Hello" "World"

In [35]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

strsplit(x, split = "!")

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [36]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

strsplit(x, split = "&!")

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [37]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

y = strsplit(x, split = "!&")

y

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [38]:
y[[1]]

[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [39]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [40]:
y[[1]][2]

[1] "available! &inthe online-help"

In [41]:
y[[1]][3]

[1] NA

In [42]:
dates = c(
  "2020-07-24",
  "2021-08-25",
  "2022-09-26",
  "2023-10-27"
)

datesplt = strsplit(dates, "-")

datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [43]:
datemat = matrix(
  unlist(datesplt),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [45]:
datematrix = matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [46]:
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [47]:
strsplit("HELLO", split = "")

[[1]]
[1] "H" "E" "L" "L" "O"

In [48]:
x = "R course 24.07.2022"

nchar(x)

[1] 19

In [49]:
y = "Number of participants: 25"

nchar(y)

[1] 26

In [50]:
x = "R course 24.07.2022"

nzchar(x)

[1] TRUE

In [51]:
y = c("Apple", "", "Cake")

y

[1] "Apple" ""      "Cake"

In [52]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [53]:
x = c("Apple", "Banana", "Cake")

nchar(x)

[1] 5 6 4

In [54]:
y = c(2, 4, 6)

nchar(y)

[1] 1 1 1

In [55]:
z = c(11, 222, 3333)

nchar(z)

[1] 2 3 4

In [56]:
z1 = c(1.1, 2.22, 3.333)

nchar(z1)

[1] 3 4 5

In [57]:
x = "R course will start from 24.07.2022"

toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [58]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

tolower(z)

[1] "indian institute of technology"