In [3]:
x = matrix( nrow=4, ncol=3, data=c(1:12) )
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [5]:
#Rename rows and columns
rownames(x) = c("r1", "r2", "r3", "r4")
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [6]:
x = matrix ( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [7]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [9]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [10]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [11]:
xt = t (x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [12]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [13]:
rowSums(x)
colSums(x)

[1]  6  8 10 12

[1] 10 26

In [14]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

rowMeans (x)
colMeans (x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

In [15]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [17]:
#Access to rows
x[3,]

#Access to columns
x[,2]

#Access to submatrices
x[4:5, 2:3]

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [18]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [25]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [26]:
#Addition
x + 5

#Subtraction
x - 5

#Multiplication
x * 5

#Divison
x/2

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [28]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [29]:
x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [30]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
4*x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [31]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [32]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [33]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [34]:
x%*%y
y%*%x

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [35]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
t (x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [36]:
t(x) %*% x

x %*% t(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [37]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
t (x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [38]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [40]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y
rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [41]:
y = matrix( nrow = 2, ncol = 2, byrow = T,
data = c(84,100,100,120))
y
solve (y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [43]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [45]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [46]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [52]:
x = c(8, 18)
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [53]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [54]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

In [56]:
x = c(8,18)
(x < 10) & (x > 2)

[1]  TRUE FALSE

In [57]:
x = 1:6 # Generates x=1,2,3,4,5,6
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [58]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [59]:
x = 1:6
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [60]:
x[(x > 2) | (x < 5)]

[1] 1 2 3 4 5 6

In [62]:
x = 1:6
(x[1] > 2) & (x[1] < 5)

[1] FALSE

In [65]:
x = TRUE
y = FALSE
x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

In [66]:
x = 5
Logical1 = (x > 2)
Logical1
is.logical(Logical1)

[1] TRUE

[1] TRUE

In [67]:
Logical2 = (x < 10)
Logical2
is.logical(Logical2)

[1] TRUE

[1] TRUE

In [68]:
Logical3 = (x != 5)
Logical3
is.logical(Logical3)

[1] FALSE

[1] TRUE

In [69]:
x = 5
Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)
Logical5 = (3*x <20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

In [71]:
8 > 7
7 < 5
 7 > 7
 7 >= 7
 8 < 8
 8 <= 8
 8 != 9
 9 != 9
 7 == 7
 7 == 8
 x = TRUE
 !X

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

ERROR: Error: object 'X' not found

In [72]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [74]:
isTRUE(8 < 6)
isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE